name: Publish release on github
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        go: 
          - '1.20'  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: run script
        run: echo ${{ github.event.release.tag_name }}
      - name: checkout qe-platform repo
        run: |
          cat <<EOF > build-qe-images.sh
          ---
          echo "success"
          EOF
      - name: run the script
        run: build-qe-images.sh
      
