name: Publish release on github
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        go: 
          - '1.20'  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: get tag
        run: echo ${{ github.event.release.tag_name }}
      - name: write script
        run: |
          cat <<EOF > build-qe-images.sh
          ---
          echo "success"
          EOF
      - name: run ls
        run: ls
      - name: check script
        run: |
          cat build-qe-images.sh
          chmod +x build-qe-images.sh
      - name: run script
        run: |
          ./build-qe-images.sh 
          
      
