name: tag test
on:
  push:
    tags:
      - '*'
env:
  REGISTRY_USER: rhn_support_lul
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.password }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        go: 
          - '1.20'  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: login quay
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}  
          registry: ${{ env.IMAGE_REGISTRY }}
      - name: write script
        run: |
          cat > build-qe-images.sh << EOF
          echo $1
          echo "success"
          echo "test"
          EOF
        shell: bash
      - name: run ls
        run: ls
      - name: check script
        run: |
          cat build-qe-images.sh
          chmod +x build-qe-images.sh
        shell: bash
      - name: run script
        env:
            TAG_CONTEXT: ${{ toJson(github.ref_name) }}
        run: |
          echo "$TAG_CONTEXT"
          ./build-qe-images.sh  $TAG_CONTEXT
        shell: bash
          
      
