name: mytest
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: check pwd
        run: |
          ls
          pwd
          mkdir mytest
          cd  mytest
          pwd
      - name: check pwd again
        working-directory: mytest
        run: |
          ls
          pwd
